server:
  port: ${PORT:8080}  # Port dynamique Railway

spring:
  application:
    name: MyIBC

okta:
  oauth2:
    issuer: https://auth-myibc.us.auth0.com/
    client-id: ${YOUR_CLIENT_ID}
    client-secret: ${YOUR_CLIENT_SECRET}

  #Configuration de la base de donnée
  datasource:
    url: ${JDBC_DATABASE_URL}  # ✅ Utilisation de la variable d’environnement
    username: ${JDBC_DATABASE_USERNAME}  # ✅ Utilisation de la variable d’environnement$
    password: ${JDBC_DATABASE_PASSWORD}  # ✅ Utilisation de la variable d’environnement $
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  frontend-url: ${FRONTEND_URL}  # 🔁 Mets ton vrai domaine ici
  jwt:
    secret: ${JWT_SECRET}     # ✅ Utilisation de la variable d’environnement
    expiration: 7200000