server:
  port: ${PORT:8080}  # Port dynamique Railway

spring:
  application:
    name: MyIBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  frontend-url: https://my-ibc-frontend.vercel.app # 🔁 Mets ton vrai domaine ici
  jwt:
    secret: ${JWT_SECRET}     # ✅ Utilisation de la variable d’environnement
    expiration: 7200000
