server:
  port: ${PORT:8080}  # Port dynamique Railway

spring:
  application:
    name: MyIBC


logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.app.MyIBC: TRACE

okta:
  oauth2:
    client-id: ${YOUR_CLIENT_ID}
    client-secret: ${YOUR_CLIENT_SECRET}
    issuer: ${ISSURER_URI}


  #Configuration de la base de donnée
  datasource:
    url: ${JDBC_DATABASE_URL}  # ✅ Utilisation de la variable d’environnement
    username: ${JDBC_DATABASE_USERNAME}  # ✅ Utilisation de la variable d’environnement$
    password: ${JDBC_DATABASE_PASSWORD}  # ✅ Utilisation de la variable d’environnement $
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  frontend-url: https://my-ibc-frontend.vercel.app # 🔁 Mets ton vrai domaine ici
